services:
  # Databases
  db:
    image: postgis/postgis:18-3.6
    # restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: belimang
      POSTGRES_SSLMODE: disable
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - belimang-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d belimang -h localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  # PostgreSQL's simple web interface
  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
    networks:
      - belimang-network

  # MinIO
  minio:
    image: minio/minio:latest
    container_name: belimang-minio
    environment:
      - MINIO_ENDPOINT:localhost:9000
      - MINIO_ACCESS_KEY:minioadmin
      - MINIO_SECRET_KEY:minioadmin123
      - MINIO_USE_SSL:false
      - MINIO_BUCKET_NAME:belimang-files
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - belimang-network
    command: server /data --console-address ":9001"

  # Go API service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - 8080:8080
    volumes:
      - ./app:/app
    networks:
      - belimang-network

volumes:
  pgdata:
  minio_data:

networks:
  belimang-network:
    driver: bridge
