services:
  # Databases
  db:
    image: postgres:17.6
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: rahasiahehe
    volumes:
      - pgdata:/var/lib/postgresql/data

  # PostgreSQL's simple web interface
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  pgdata:
