# 
apiVersion: v1
kind: Pod
metadata:
  name: belimang-postgres
  labels:
    app: belimang-postgres
spec:
  containers:
    - name: postgres
      image: postgis/postgis:18-3.6
      ports:
        - containerPort: 5432
      resources:
        requests:
          cpu: 250m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 256Mi
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres -d belimang -h localhost"]
        interval: 5s
        timeout: 5s
        retries: 10
        start_period: 10s
      env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_DB
          value: belimang
        - name: POSTGRES_HOST
          value: localhost
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_SSLMODE
          value: disable
      volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
  volumes:
    - name: postgres-data
      emptyDir: {}

