// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: images.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getImage = `-- name: GetImage :one
SELECT object_key FROM images WHERE object_key = $1
`

func (q *Queries) GetImage(ctx context.Context, objectKey pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getImage, objectKey)
	var object_key pgtype.UUID
	err := row.Scan(&object_key)
	return object_key, err
}

const insertImage = `-- name: InsertImage :exec
INSERT INTO images (
  object_key
) VALUES (
  $1
)
`

func (q *Queries) InsertImage(ctx context.Context, objectKey pgtype.UUID) error {
	_, err := q.db.Exec(ctx, insertImage, objectKey)
	return err
}
