// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: merchants.sql

package db

import (
	"context"
)

const createMerchant = `-- name: CreateMerchant :exec
INSERT INTO merchants (
  name, merchant_category, image_url, location
) VALUES (
  $1, $2, $3, $4
)
`

type CreateMerchantParams struct {
	Name             string
	MerchantCategory MerchantCategory
	ImageUrl         string
	Location         interface{}
}

func (q *Queries) CreateMerchant(ctx context.Context, arg CreateMerchantParams) error {
	_, err := q.db.Exec(ctx, createMerchant,
		arg.Name,
		arg.MerchantCategory,
		arg.ImageUrl,
		arg.Location,
	)
	return err
}
