// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
)

const createAdmin = `-- name: CreateAdmin :exec
INSERT INTO users (
  username, password, email, role
) VALUES (
  $1, $2, $3, 'admin'
)
`

type CreateAdminParams struct {
	Username string
	Password string
	Email    string
}

func (q *Queries) CreateAdmin(ctx context.Context, arg CreateAdminParams) error {
	_, err := q.db.Exec(ctx, createAdmin, arg.Username, arg.Password, arg.Email)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (
  username, password, email, role
) VALUES (
  $1, $2, $3, 'user'
)
`

type CreateUserParams struct {
	Username string
	Password string
	Email    string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser, arg.Username, arg.Password, arg.Email)
	return err
}

const getAdminByUsername = `-- name: GetAdminByUsername :one
SELECT username, password, email, role FROM users where username = $1
`

func (q *Queries) GetAdminByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getAdminByUsername, username)
	var i User
	err := row.Scan(
		&i.Username,
		&i.Password,
		&i.Email,
		&i.Role,
	)
	return i, err
}
